#cloud-config
# based on: https://stackoverflow.com/a/62540068/312124

apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - certbot

# Enable ipv4 forwarding, required on CIS hardened machines
write_files:
  - path: /etc/sysctl.d/enabled_ipv4_forwarding.conf
    content: |
      net.ipv4.conf.all.forwarding=1

# create the docker group
groups:
  - docker

# Add default auto created user to docker group
system_info:
  default_user:
    groups: [ docker ]

power_state:
  mode: reboot
  message: Restarting after installing docker & docker-compose

runcmd:
  - |
    git clone https://github.com/HiEventsDev/hi.events.git /root/hi.events
    cd /root/hi.events/docker/all-in-one
    JWT_SECRET_CALC=$(openssl rand -base64 32)
    APP_KEY_CALC="$(openssl rand -base64 32)"
    sed -i "s|^APP_KEY=.*|APP_KEY=\"base64:$APP_KEY_CALC\"|" .env
    sed -i "s|^JWT_SECRET=.*|JWT_SECRET=\"$JWT_SECRET_CALC\"|" .env
    docker run -d --name=nginx-proxy-manager \
      -p 80:80 -p 443:443 -p 81:81 \
      -v /root/nginx-proxy-manager/data:/data \
      -v /root/nginx-proxy-manager/letsencrypt:/etc/letsencrypt \
      jc21/nginx-proxy-manager